version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
  machine-executor:
    machine:
      image: ubuntu-2004:202010-01    

jobs:
  install_dependencies:
    executor: docker-executor
    steps:
      - run: echo "install any dependencies.."
  run_VT:
    executor: machine-executor
    steps:
      - checkout
      - run: 
          environment:
            DEPLOY_FILE: $DEPLOY_FILE
            VT_DOCKER_NAME: $VT_DOCKER_NAME
            VT_DOCKER_IMAGE: << marklawimperial/verification-tool >>
            VT_FILES_PATH: $VT_FILES_PATH
          command: |
            echo "run VT" 
            echo "" 
            docker pull ${VT_DOCKER_IMAGE}
  run_DPT:
    executor: docker-executor
    steps:
      - run: echo "run DPT"
  run_CTT:
    executor: docker-executor
    steps:
      - run: echo "run CTT"
  fetch_blueprint_from_TL:
    executor: docker-executor
    steps:
      - run: echo "fetch blueprint from TL"
  opera_deploy:
    executor: docker-executor
    steps:
      - run: echo "opera deploy"
  cleanup:
    executor: docker-executor
    steps:
      - run: 
          command: echo "cleaning up the workspace"
          when: always
    
workflows:
  cloudstash:
    jobs:
      - install_dependencies
      - run_VT:
          requires:
            - install_dependencies
      - run_DPT:
          requires:
            - run_VT
      - run_CTT:
          requires:
            - run_DPT
      - fetch_blueprint_from_TL:
          requires:
            - run_CTT
      - opera_deploy:
          requires:
            - fetch_blueprint_from_TL
      - cleanup:
          requires:
            - opera_deploy
