version: 2.1

jobs:
  install_dependencies:
    steps:
      - run: echo "install dependencies"
  run_VT:
    steps:
      - run: echo "run VT"
  run_DPT:
    steps:
      - run: echo "run DPT"
  run_CTT:
    steps:
      - run: echo "run CTT"
  fetch_blueprint_from_TL:
    steps:
      - run: echo "fetch blueprint from TL"
  opera_deploy:
    steps:
      - run: echo "opera deploy"
  cleanup:
    steps:
      - run: echo "cleaning up the workspace"
        when: always
    
workflows:
  cloudstash:
    jobs:
      - install_dependencies
      - run_VT:
          requires:
            - install_dependencies
      - run_DPT:
          requires:
            - run_VT
      - run_CTT:
          requires:
            - run_DPT
      - fetch_blueprint_from_TL:
          requires:
            - run_CTT
      - opera_deploy:
          requires:
            - fetch_blueprint_from_TL
      - cleanup:
          requires:
            - opera_deploy
