version: 2.1

jobs:
  install_dependencies:
    steps:
      - run:
        command: sh 'echo install dependencies'
  run_VT:
    steps:
      - run:
        command: sh 'echo run VT'
  run_DPT:
    steps:
      - run:
        command: sh 'echo run DPT'
  run_CTT:
    steps:
      - run:
        command: sh 'echo run CTT'
  fetch_blueprint_from_TL:
    steps:
      - run:
        command: sh 'fetch blueprint from TL'
  opera_deploy:
    steps:
      - run:
        command: sh 'opera deploy'
  cleanup:
    steps:
      - run:
        when: always
        command: sh 'cleaning up the workspace'
    
workflows:
  cloudstash:
    jobs:
      - install_dependencies
      - run_VT:
          requires:
            - install_dependencies
      - run_DPT:
          requires:
            - run_VT
      - run_CTT:
          requires:
            - run_DPT
      - fetch_blueprint_from_TL:
          requires:
            - run_CTT
      - opera_deploy:
          requires:
            - fetch_blueprint_from_TL
      - cleanup:
          requires:
            - opera_deploy
